# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: kefo.no
email: kenneth@kefo.no
description: >- # this means to ignore newlines until "baseurl:"
  kefo.no is a hobby firm that does app development and personal projects.
  If time allows it, I'm open to take on new projects.
  Currently doing a Master in Software Engineering <a href="http://www.uib.no">@uib</a>, 
  with a Bachelor's in Computer Security from <a href="http://www.uib.no">@uib</a>
  <br><br>
  <img src="/assets/img/kefo.png" width="200" height="200">

  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  spydx


author:
  name: Kenneth Fossen
  email: kenneth@kefo.no
  about: |
    Hi, I'm Kenneth, a MsC Student in Software Engineering at UiB.
    Currently studying Microservice architecture and security.

  social:
    github: spydx
    email: kenneth@kefo.no
    instagram: spydx
    twitter: xdyps


theme: jekyll-theme-hydejack
plugins:
  - jekyll-avatar

favicon: /favicon.ico
apple_touch_icon: /assets/img/kefo.png
accent_image: /assets/img/sidebar-bg.png
#accent_color: rgb(79,177,186)
theme_color:  rgb(25,55,71)
clap_button: false

menu:
  - title: Projects
    url:   /projects/
  - title: About
    url:   /about/
  - title: "@PictureBlog"
    url: https://blog.kefo.no/
  - title: "@TechBlog"
    url: https://tech.kefo.no/

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

legal:
  - title: Projects
    url:  /projects/
  - title: About
    url:  /about/

kramdown:
  math_engine:         katex
  math_engine_opts:    {}